name: 👓 Scan
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '00 16 * * *'
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  clippy:
    name: 📎 Run clippy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7

      - name: 🦀 Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: 📦 Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: 📎 Run clippy
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: ⬆️ Upload results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true